const demoOrders = [
  { id: 'PED-0027', client: 'Nativa Studio', service: '80 camisas polo bordadas', status: 'production', owner: 'Carlos Gómez', due: '29 sep 2026', dueIso: '2026-09-29', quote: 'PRE-0042' },
  { id: 'PED-0026', client: 'Cima Running Club', service: '60 camisetas deportivas', status: 'design', owner: 'María Rodríguez', due: '28 sep 2026', dueIso: '2026-09-28', quote: 'PRE-0041' },
  { id: 'PED-0025', client: 'Grupo Horizonte', service: '50 kits corporativos', status: 'quality', owner: 'Equipo de producción', due: '26 sep 2026', dueIso: '2026-09-26', quote: 'PRE-0037' },
  { id: 'PED-0024', client: 'Andrés Salazar', service: '12 camisas ejecutivas', status: 'ready', owner: 'Carlos Gómez', due: '25 sep 2026', dueIso: '2026-09-25', quote: 'PRE-0035' },
  { id: 'PED-0023', client: 'Taller Aurora', service: '10 textiles personalizados', status: 'delivered', owner: 'María Rodríguez', due: '20 sep 2026', dueIso: '2026-09-20', quote: 'PRE-0034' }
];
const state = { orders: JSON.parse(localStorage.getItem('da-orders')) || demoOrders };
const labels = { confirmed: 'Confirmado', materials: 'Pendiente de materiales', design: 'En diseño', production: 'En producción', quality: 'Control de calidad', ready: 'Listo para entregar', delivered: 'Entregado', paused: 'Pausado' };
const $ = (selector) => document.querySelector(selector);
function render() { const query = $('#searchInput').value.trim().toLowerCase(); const status = $('#statusFilter').value; const rows = state.orders.filter((order) => (!query || [order.id, order.client, order.service, order.owner].some((value) => value.toLowerCase().includes(query))) && (status === 'all' || order.status === status)); $('#orderTableBody').innerHTML = rows.map((order, index) => `<tr><td><input type="checkbox" aria-label="Seleccionar ${order.id}"></td><td><div class="client-cell"><span class="client-avatar ${['yellow','blue','pink'][index % 3]}">◫</span><div><strong>${order.id}</strong><small>${order.quote ? `Desde ${order.quote}` : 'Pedido manual'}</small></div></div></td><td>${order.client}</td><td>${order.service}</td><td><span class="status-pill ${order.status}">${labels[order.status]}</span></td><td>${order.owner}</td><td><span class="due-date ${order.status !== 'delivered' && new Date(order.dueIso) < new Date() ? 'late' : ''}">${order.due}</span></td><td><button class="row-action" type="button" aria-label="Abrir ${order.id}" data-order="${order.id}">···</button></td></tr>`).join(''); $('#emptyState').hidden = rows.length > 0; $('#resultCount').textContent = `${rows.length} ${rows.length === 1 ? 'pedido' : 'pedidos'}`; $('#activeOrders').textContent = state.orders.filter((order) => !['delivered', 'paused'].includes(order.status)).length; $('#dueOrders').textContent = state.orders.filter((order) => !['delivered', 'paused'].includes(order.status) && new Date(order.dueIso) <= new Date('2026-09-29')).length; $('#deliveredOrders').textContent = state.orders.filter((order) => order.status === 'delivered').length; $('#navOrderCount').textContent = state.orders.length; $('#clearFilter').hidden = !query && status === 'all'; $('#filterCount').textContent = status === 'all' ? '' : '1'; }
function openDrawer(order = null) { $('#orderForm').reset(); $('#orderDrawer').classList.add('open'); $('#orderDrawer').setAttribute('aria-hidden', 'false'); $('#drawerBackdrop').hidden = false; $('#orderDue').value = order?.dueIso || new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10); if (order) { $('#orderQuote').value = order.quote || ''; $('#orderClient').value = order.client; $('#orderService').value = order.service; $('#orderStatus').value = order.status; $('#orderOwner').value = order.owner; } setTimeout(() => $('#orderClient').focus(), 200); }
function closeDrawer() { $('#orderDrawer').classList.remove('open'); $('#orderDrawer').setAttribute('aria-hidden', 'true'); $('#drawerBackdrop').hidden = true; }
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 3000); }
$('#newOrderButton').addEventListener('click', () => openDrawer()); $('#drawerClose').addEventListener('click', closeDrawer); $('#cancelButton').addEventListener('click', closeDrawer); $('#drawerBackdrop').addEventListener('click', closeDrawer); $('#searchInput').addEventListener('input', render); $('#statusFilter').addEventListener('change', render); $('#clearFilter').addEventListener('click', () => { $('#searchInput').value = ''; $('#statusFilter').value = 'all'; render(); }); $('#orderTableBody').addEventListener('click', (event) => { const button = event.target.closest('[data-order]'); if (button) openDrawer(state.orders.find((order) => order.id === button.dataset.order)); });
$('#orderQuote').addEventListener('change', (event) => { const quote = event.target.value; const data = { 'PRE-0042': ['Nativa Studio', '80 camisas polo bordadas'], 'PRE-0041': ['Cima Running Club', '60 camisetas deportivas'] }[quote]; if (data) { $('#orderClient').value = data[0]; $('#orderService').value = data[1]; } });
$('#orderForm').addEventListener('submit', (event) => { event.preventDefault(); const order = { id: `PED-${String(28 + state.orders.length).padStart(4, '0')}`, client: $('#orderClient').value.trim(), service: $('#orderService').value.trim(), status: $('#orderStatus').value, owner: $('#orderOwner').value, dueIso: $('#orderDue').value, due: new Date(`${$('#orderDue').value}T12:00:00`).toLocaleDateString('es-CO', { day: '2-digit', month: 'short', year: 'numeric' }), quote: $('#orderQuote').value }; if (!order.client || !order.service) return toast('Completa el cliente y la descripción del servicio.'); state.orders.unshift(order); localStorage.setItem('da-orders', JSON.stringify(state.orders)); render(); closeDrawer(); toast('Pedido creado correctamente.'); });
$('#exportButton').addEventListener('click', () => { const header = 'Numero,Cliente,Servicio,Estado,Responsable,Entrega'; const rows = state.orders.map((order) => [order.id, order.client, order.service, labels[order.status], order.owner, order.due].map((value) => `"${value}"`).join(',')); const blob = new Blob([[header, ...rows].join('\n')], { type: 'text/csv;charset=utf-8;' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'pedidos-da.csv'; link.click(); URL.revokeObjectURL(link.href); toast('Pedidos exportados en formato CSV.'); });
const sidebar = $('#sidebar'); $('.mobile-menu').addEventListener('click', (event) => { const open = sidebar.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', String(open)); }); $('.sidebar-close').addEventListener('click', () => sidebar.classList.remove('open')); render();
