const demoQuotes = [
  { id: 'PRE-0042', client: 'Nativa Studio', service: 'Uniformes corporativos', status: 'approved', due: '30 sep 2026', total: 4680000, concepts: [{ service: 'Camisas polo', description: 'Polo bordado, tela dry fit', quantity: 80, price: 58500 }], notes: 'Logo en pecho izquierdo.' },
  { id: 'PRE-0041', client: 'Cima Running Club', service: 'Uniformes deportivos', status: 'sent', due: '28 sep 2026', total: 3120000, concepts: [{ service: 'Camiseta deportiva', description: 'Sublimación total', quantity: 60, price: 52000 }], notes: '' },
  { id: 'PRE-0040', client: 'Laura Méndez', service: 'Sublimación creativa', status: 'review', due: '25 sep 2026', total: 890000, concepts: [{ service: 'Textiles personalizados', description: 'Muestra de colección', quantity: 10, price: 89000 }], notes: 'Esperando confirmación de colores.' },
  { id: 'PRE-0039', client: 'Andrés Salazar', service: 'Confección de camisas', status: 'draft', due: '02 oct 2026', total: 1260000, concepts: [{ service: 'Camisa ejecutiva', description: 'Algodón premium', quantity: 12, price: 105000 }], notes: '' },
  { id: 'PRE-0038', client: 'Grupo Horizonte', service: 'Uniformes corporativos', status: 'rejected', due: '18 sep 2026', total: 7250000, concepts: [{ service: 'Kit corporativo', description: 'Camisa + pantalón', quantity: 50, price: 145000 }], notes: '' }
];
const state = { quotes: JSON.parse(localStorage.getItem('da-quotes')) || demoQuotes, concepts: [] };
const labels = { draft: 'Borrador', sent: 'Enviado', review: 'En revisión', approved: 'Aprobado', rejected: 'Rechazado', expired: 'Vencido' };
const money = (value) => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', maximumFractionDigits: 0 }).format(value);
const $ = (selector) => document.querySelector(selector);

function render() {
  const query = $('#searchInput').value.trim().toLowerCase(); const status = $('#statusFilter').value;
  const rows = state.quotes.filter((quote) => (!query || [quote.id, quote.client, quote.service].some((value) => value.toLowerCase().includes(query))) && (status === 'all' || quote.status === status));
  $('#quoteTableBody').innerHTML = rows.map((quote, index) => `<tr><td><input type="checkbox" aria-label="Seleccionar ${quote.id}"></td><td><div class="client-cell"><span class="client-avatar ${['yellow','blue','pink'][index % 3]}">▤</span><div><strong>${quote.id}</strong><small>Creado recientemente</small></div></div></td><td>${quote.client}</td><td>${quote.service}</td><td><span class="status-pill ${quote.status}">${labels[quote.status]}</span></td><td>${quote.due}</td><td><strong>${money(quote.total)}</strong></td><td><button class="row-action" type="button" aria-label="Abrir ${quote.id}" data-quote="${quote.id}">···</button></td></tr>`).join('');
  $('#emptyState').hidden = rows.length > 0; $('#resultCount').textContent = `${rows.length} ${rows.length === 1 ? 'presupuesto' : 'presupuestos'}`; $('#totalQuotes').textContent = state.quotes.length; $('#pendingQuotes').textContent = state.quotes.filter((quote) => ['sent', 'review'].includes(quote.status)).length; $('#approvedValue').textContent = money(state.quotes.filter((quote) => quote.status === 'approved').reduce((sum, quote) => sum + quote.total, 0)); $('#navQuoteCount').textContent = state.quotes.length; $('#clearFilter').hidden = !query && status === 'all'; $('#filterCount').textContent = status === 'all' ? '' : '1';
}
function addConcept(concept = {}) { const id = Date.now() + Math.random(); state.concepts.push({ id, service: concept.service || '', description: concept.description || '', quantity: concept.quantity || 1, price: concept.price || 0 }); renderConcepts(); }
function renderConcepts() { $('#concepts').innerHTML = state.concepts.map((concept) => `<div class="concept-row" data-concept="${concept.id}"><label>Servicio<input data-field="service" value="${concept.service}" placeholder="Sublimación"></label><label>Descripción<input data-field="description" value="${concept.description}" placeholder="Detalle del trabajo"></label><label>Cantidad<input data-field="quantity" type="number" min="1" value="${concept.quantity}"></label><label>Precio unitario<input data-field="price" type="number" min="0" value="${concept.price}"></label><button class="remove-concept" type="button" aria-label="Eliminar concepto">×</button></div>`).join(''); calculateTotals(); }
function calculateTotals() { const subtotal = state.concepts.reduce((sum, concept) => sum + (Number(concept.quantity) || 0) * (Number(concept.price) || 0), 0); const discount = Number($('#discount').value) || 0; const tax = Number($('#tax').value) || 0; const discounted = subtotal * (1 - discount / 100); $('#subtotal').textContent = money(subtotal); $('#total').textContent = money(discounted * (1 + tax / 100)); }
function openDrawer() { $('#quoteForm').reset(); $('#quoteDueDate').value = new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 10); state.concepts = []; addConcept(); $('#quoteDrawer').classList.add('open'); $('#quoteDrawer').setAttribute('aria-hidden', 'false'); $('#drawerBackdrop').hidden = false; setTimeout(() => $('#quoteClient').focus(), 200); }
function closeDrawer() { $('#quoteDrawer').classList.remove('open'); $('#quoteDrawer').setAttribute('aria-hidden', 'true'); $('#drawerBackdrop').hidden = true; }
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('show'); setTimeout(() => $('#toast').classList.remove('show'), 3000); }

$('#newQuoteButton').addEventListener('click', openDrawer); $('#drawerClose').addEventListener('click', closeDrawer); $('#cancelButton').addEventListener('click', closeDrawer); $('#drawerBackdrop').addEventListener('click', closeDrawer); $('#searchInput').addEventListener('input', render); $('#statusFilter').addEventListener('change', render); $('#clearFilter').addEventListener('click', () => { $('#searchInput').value = ''; $('#statusFilter').value = 'all'; render(); }); $('#addConcept').addEventListener('click', () => addConcept()); $('#discount').addEventListener('input', calculateTotals); $('#tax').addEventListener('input', calculateTotals);
$('#concepts').addEventListener('input', (event) => { const row = event.target.closest('[data-concept]'); const concept = state.concepts.find((item) => String(item.id) === row.dataset.concept); concept[event.target.dataset.field] = event.target.type === 'number' ? Number(event.target.value) : event.target.value; calculateTotals(); }); $('#concepts').addEventListener('click', (event) => { const button = event.target.closest('.remove-concept'); if (!button) return; const row = button.closest('[data-concept]'); state.concepts = state.concepts.filter((concept) => String(concept.id) !== row.dataset.concept); renderConcepts(); });
$('#quoteTableBody').addEventListener('click', (event) => { const button = event.target.closest('[data-quote]'); if (button) toast(`El detalle de ${button.dataset.quote} estará disponible con el historial de versiones.`); });
$('#quoteForm').addEventListener('submit', (event) => { event.preventDefault(); const totalText = $('#total').textContent; const quote = { id: `PRE-${String(43 + state.quotes.length).padStart(4, '0')}`, client: $('#quoteClient').value, service: state.concepts[0]?.service || 'Servicio personalizado', status: $('#quoteStatus').value, due: new Date(`${$('#quoteDueDate').value}T12:00:00`).toLocaleDateString('es-CO', { day: '2-digit', month: 'short', year: 'numeric' }), total: Number(totalText.replace(/[^0-9]/g, '')) || 0, concepts: state.concepts, notes: $('#quoteNotes').value }; if (!quote.client || !state.concepts.length || quote.total <= 0) return toast('Completa el cliente y agrega conceptos con valor.'); state.quotes.unshift(quote); localStorage.setItem('da-quotes', JSON.stringify(state.quotes)); render(); closeDrawer(); toast('Presupuesto creado correctamente.'); });
$('#exportButton').addEventListener('click', () => { const header = 'Numero,Cliente,Servicio,Estado,Vencimiento,Total'; const rows = state.quotes.map((quote) => [quote.id, quote.client, quote.service, labels[quote.status], quote.due, quote.total].map((value) => `"${value}"`).join(',')); const blob = new Blob([[header, ...rows].join('\n')], { type: 'text/csv;charset=utf-8;' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'presupuestos-da.csv'; link.click(); URL.revokeObjectURL(link.href); toast('Presupuestos exportados en formato CSV.'); });
const sidebar = $('#sidebar'); $('.mobile-menu').addEventListener('click', (event) => { const open = sidebar.classList.toggle('open'); event.currentTarget.setAttribute('aria-expanded', String(open)); }); $('.sidebar-close').addEventListener('click', () => sidebar.classList.remove('open'));
render();
